Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

MethodLength:
  Max: 15

AllCops:
  Include:
    - Gemfile
    - lib/tasks/*
  Exclude:
    - db/**/*
    - vendor/**/*
    - config/**/*
    - script/**/*
